if: (type = push AND branch IN (main, develop)) OR (type = pull_request)
language: android
jdk: oraclejdk11
os: linux
dist: trusty
env:
  global:
    - TARGET_VERSION=31
    - ANDROID_BUILD_TOOLS_VERSION=31.0.0
    - ANDROID_HOME=~/android-sdk

android:
  components:
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$TARGET_VERSION
    - platform-tools
    - tools
    - extra-google-googleplayservices
    - extra-google-m2repository
    - extra-android-m2repository

before_install:
  # Get Java 11 compatible tools: https://stackoverflow.com/a/68534598/4407321
  - touch $HOME/.android/repositories.cfg
  - wget "https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip" -O commandlinetools.zip
  - unzip commandlinetools.zip -d $ANDROID_HOME/
  - yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager "platforms;android-${TARGET_VERSION}" --sdk_root=$ANDROID_HOME
  - yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager "build-tools;${ANDROID_BUILD_TOOLS_VERSION}" --sdk_root=$ANDROID_HOME

  - openssl aes-256-cbc -md sha256 -k $APPID_DECRYPTION_KEY -in keys.properties.enc -out keys.properties -d
  - chmod +x gradlew
  - gem install bundler
  - rvm install 2.7.2
  - bundle install

jobs:
  include:
    #     - name: "Test app"
    #       script: bundle exec fastlane unitTests
    - name: "Build Staging MFE"
      script: bundle exec fastlane buildStagingmfe
      if: (head_branch NOT IN (main, develop))

    - name: "Build and Deploy Staging MFE"
      script: bundle exec fastlane distributeStagingmfe
      if: (head_branch IS blank AND branch IN (main, develop, release/*))

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
