name: Android Pull Request

on:
  pull_request:
#    types: [ review_requested ]
    branches: [ main, develop, releases/** ]

jobs:
  build-stagingmfe:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: "Build StagingMFE"
        uses: maierj/fastlane-action@v2.2.0
        with:
          lane: 'build'

      - name: Store artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: app/build/outputs/apk/stagingmfe/release/app-stagingmfe-release.apk
