name: CI

on:
  push:

jobs:
  codesmell:
    runs-on: ubuntu-latest
    steps:
    - name: skip-job
      if: ${{ steps.validation.outcome != 'success' }}
      uses: actions/github-script@v3
      with:
        script:
          core.setFailed('Resource is less than or equal to 10')  
