name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  codesmell:
    name: Code Smell (Detekt, CheckStyle, Lint)
    uses: ./.github/workflows/prepare.yml
    with:
      commands: ./gradlew build
